version: '3.8'
services:
  node-streznik:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "80:3000"