version: '3.8'
services:
  node-streznik:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: projekt-backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "80:3000"
    container_name: projekt-frontend