version: '3.8'
services:
  node-streznik:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: node-streznik
    networks:
      - projekt-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "80:3000"
    container_name: frontend
    networks:
      - projekt-network

  database:
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "3306:3306"
    container_name: database
    networks:
      - projekt-network
    volumes:
      - /home/projekt-website/db-data:/var/lib/mysql

networks:
  projekt-network: